### ISSUE TITLE
There was a problem executing your code. I wonder if you can help me

### ISSUE THREAD

**Issue by lagokun** [Kaiseem/QueryOTR#3]
The following error occurred while executing the code. 
please help me😥

Traceback (most recent call last):
  File "main.py", line 103, in <module>
    g_grad_scale=g_grad_scaler)
  File "/workspace/QueryOTR/engine.py", line 53, in train_one_epoch
    D_losses.backward()
  File "/opt/conda/envs/hgonet/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/hgonet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Kaiseem** [comment]
Hi, this bug usually occurs in the operation "+=", which is widely used in 
https://github.com/Kaiseem/QueryOTR/blob/972eaba6b040b9e292d3827a5dd5e69edeffe876/models/CNNDis.py#L119

You can simply try to modify "loss += something" to "loss = loss + something"

However, i cannot reimplement this bug in my computer, the same code in 
https://github.com/NVlabs/MUNIT/blob/a82e222bc359892bd0f522d7a0f1573f3ec4a485/networks.py#L53

If the bug cannot be fixed, pls let me know

**Comment by lagokun** [comment]
Thank you for your quick reply!, I changed the code as you said and turned it around, but the same error appears. (def calc_gen_loss was also modified.)

   def calc_dis_loss(self, input_fake, input_real):
        # calculate the loss to train D
        input_real.requires_grad_()
        outs0 = self.forward(input_fake)
        outs1 = self.forward(input_real)
        loss = 0
        for it, (out0, out1) in enumerate(zip(outs0, outs1)):
            if self.gan_type == 'lsgan':
                loss = loss + torch.mean((out0 - 0) ** 2) + torch.mean((out1 - 1) ** 2)
            elif self.gan_type == 'nsgan':
                all0 = Variable(torch.zeros_like(out0.data).cuda(), requires_grad=False)
                all1 = Variable(torch.ones_like(out1.data).cuda(), requires_grad=False)
                loss = loss + torch.mean(F.binary_cross_entropy(F.sigmoid(out0), all0) +
                                   F.binary_cross_entropy(F.sigmoid(out1), all1))
            elif self.gan_type == 'hinge':
                loss = loss + F.relu(1.0+out0).mean()+F.relu(1.0-out1).mean()
            elif self.gan_type == 'ralsgan':
                loss = loss + (torch.mean((out0 - torch. mean(out1,0) - 1) ** 2) + torch.mean((out1 - torch.mean(out0,0) + 1) ** 2))/2
            else:
                assert 0, "Unsupported GAN type: {}".format(self.gan_type)
                #loss+=self.r1_reg(out1,input_real)
        if self.avg_loss:
            return loss/self.num_scales
        return loss

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Kaiseem** [comment]
I don't know why.. I cannot reimplement this error, so as my colleagues. My experimental setting is Win10, GTX3090, torch 1.10.1+cu113. Maybe you can upgrade the torch and cuda?

**Comment by Kaiseem** [comment]
wish everything is ok

**Comment by lagokun** [comment]
I solved it Thank you for providing me with a good code

**Comment by MasterHow** [comment]
same question.

Traceback (most recent call last):
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\main.py", line 100, in <module>
    train_one_epoch(opts, gen, cnn_dis, criterion, train_loader, opt_g, opt_d, torch.device('cuda'), epoch,
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\engine.py", line 52, in train_one_epoch
    D_losses.backward()
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by lagokun** [comment]
Set it as similar as possible to the version provided in the code

**Comment by Kaiseem** [comment]
Unfortunately, i cannot reimplement this bug in my experimental enviroment (torch==1.10.1+cu113, GTX3090, win10). As suggested by @lagokun , you can simply upgrade the torch version, or you can set torch.autograd.set_detect_anomaly(True) before function "train_one_epoch", tell us what happen, so that we can fix it maybe.

**Comment by MasterHow** [comment]
感谢回复，我的环境是torch=1.9.0+cu113 GTX3090 win10。我加入了检测异常的函数，报错如下：

[W ..\torch\csrc\autograd\python_anomaly_mode.cpp:104] Warning: Error detected in DotBackward. Traceback of forward call that caused the error:
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\main.py", line 103, in <module>
    train_one_epoch(opts, gen, cnn_dis, criterion, train_loader, opt_g, opt_d, torch.device('cuda'), epoch,
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\engine.py", line 48, in train_one_epoch
    D_loss_dict = criterion.get_dis_loss(fake, gt, DIS)
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\losses\__init__.py", line 25, in get_dis_loss
    return {'loss_d_adversarial': discriminator.calc_dis_loss(input_fake.detach(),input_real)}
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\models\CNNDis.py", line 122, in calc_dis_loss
    outs0 = self.forward(input_fake)
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\models\CNNDis.py", line 114, in forward
    output=model(x)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\models\CNNDis.py", line 67, in forward
    x = self.conv(self.pad(x))
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\utils\parametrize.py", line 178, in get_parametrized
    return parametrization()
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\utils\parametrize.py", line 110, in forward
    x = module(x)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\nn\utils\parametrizations.py", line 92, in forward
    sigma = torch.dot(self.u, torch.mv(weight_mat, self.v))
 (function _print_stack)
Traceback (most recent call last):
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\main.py", line 103, in <module>
    train_one_epoch(opts, gen, cnn_dis, criterion, train_loader, opt_g, opt_d, torch.device('cuda'), epoch,
  File "D:\MyProject\PyThon\FlowInpainting\QueryOTR\engine.py", line 52, in train_one_epoch
    D_losses.backward()
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\TOOLKITS\miniconda\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Kaiseem** [comment]
这个bug太隐蔽了，我们这服务器linux的torch 1.7 1.9没有问题，参考 https://zhuanlan.zhihu.com/p/518144688 ，我猜测把x = self.conv(self.pad(x)) 拆成 x = self.pad(x) x = self.conv(x) 可能有用，或者是loss那那个+=改成loss = loss+xxx（但MUNIT原版没这个问题），或者
input_fake_detach = input_fake.detach()
return {'loss_d_adversarial': discriminator.calc_dis_loss(input_fake_detach, input_real)}
你试试看

**Comment by MasterHow** [comment]
好的，我测试一下，感谢您的建议！
